// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AlibabaSDK is an autogenerated mock type for the AlibabaSDK type
type AlibabaSDK struct {
	mock.Mock
}

// Upload provides a mock function with no fields
func (_m *AlibabaSDK) Upload() {
	_m.Called()
}

// NewAlibabaSDK creates a new instance of AlibabaSDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlibabaSDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlibabaSDK {
	mock := &AlibabaSDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
